/**
 * Tamanho máximo de cada campo, espelhando as colunas do banco
 * (back: Limites.java / db/apae.sql). Alterou lá, altere aqui.
 */
export const LIMITES = {
  // Pessoa / contato
  NOME_PESSOA: 120,
  TELEFONE: 20,
  EMAIL: 120,
  CPF: 14,
  CNPJ: 18,
  UF: 2,
  MUNICIPIO: 100,
  RESPONSAVEL: 120,
  OBSERVACAO_CURTA: 500,
  TEXTO_LONGO: 2000,

  // Unidade
  UNIDADE_NOME: 150,
  UNIDADE_ENDERECO: 200,
  UNIDADE_CIDADE_UF: 100,
  UNIDADE_SITE: 150,
  UNIDADE_RODAPE: 500,

  // Usuário
  USUARIO_LOGIN: 50,
  USUARIO_NOME: 60,
  USUARIO_SOBRENOME: 100,
  SENHA_MINIMO: 8,
  SENHA_MAXIMO: 72,

  // Arquivo (MB — o back também valida)
  ARQUIVO_TAMANHO_MB: 20,

  // Chat
  MENSAGEM_TEXTO: 2000,

  // Secretaria
  TAREFA_TITULO: 200,
  TAREFA_CATEGORIA: 60,
  SUBTAREFA_TEXTO: 200,

  // Agenda
  EVENTO_TITULO: 200,
  EVENTO_LOCAL: 150,
  EVENTO_PARTICIPANTES: 500,

  // Atendimentos
  ATENDIMENTO_NOME: 150,
  ATENDIMENTO_REMARCADO_MOTIVO: 200,

  // Documentos
  DOCUMENTO_NOME: 200,
  DOCUMENTO_NUMERO: 60,
  DOCUMENTO_ORGAO: 150,
  DOCUMENTO_LOCAL_GUARDADO: 200,
  DOCUMENTO_TAGS: 200,

  // Empresas
  EMPRESA_RAZAO_SOCIAL: 200,
  EMPRESA_NOME_FANTASIA: 200,
  EMPRESA_ENDERECO: 250,
  EMPRESA_OBSERVACAO: 1000,
  EMPRESA_DOCUMENTO_NOME: 60,
  EMPRESA_DOCUMENTO_OBSERVACAO: 500,
  // Projetos
  PROJETO_NOME: 150,
  PROJETO_FONTE: 120,
  PROJETO_ORGAO: 150,
  PROJETO_CONVENIO: 100,
  PROJETO_CONTA: 100,
  PROJETO_OBSERVACAO: 500,
  PLANO_DESCRICAO: 4000,
  RECURSO_DOCUMENTO_NOME: 60,
  COTACAO_ITEM_DESCRICAO: 200,
  ORDEM_NUMERO: 40,
  EXECUCAO_DOCUMENTO_NOME: 150,
  PAGAMENTO_FORNECEDOR: 200,
  PAGAMENTO_FORMA: 30,
  PENDENCIA_TITULO: 200,
  PENDENCIA_DESCRICAO: 1000,
  GERADOR_MODELO_NOME: 100,
  GERADOR_TITULO: 150,
  GERADOR_SERIE: 60,
  GERADOR_TEXTO: 100000,
  GERADOR_CAMPO_VALOR: 5000,
  GERADOR_ASSINATURAS_MAXIMO: 10,
  GERADOR_ASSINATURA_LINHAS_MAXIMO: 5,
  GERADOR_ASSINATURA_LINHA: 150,
  GERADOR_VINCULO_ROTULO: 200,
} as const;
