/** Códigos de permissão (tabela acesso.permissao no back). */
export const PERMISSOES = {
  AGENDA_LER: 'AGENDA_LER',
  AGENDA_ESCREVER: 'AGENDA_ESCREVER',
  TAREFA_LER: 'TAREFA_LER',
  TAREFA_ESCREVER: 'TAREFA_ESCREVER',
  ATENDIMENTO_LER: 'ATENDIMENTO_LER',
  ATENDIMENTO_ESCREVER: 'ATENDIMENTO_ESCREVER',
  PROJETO_LER: 'PROJETO_LER',
  PROJETO_ESCREVER: 'PROJETO_ESCREVER',
  DOCUMENTO_LER: 'DOCUMENTO_LER',
  DOCUMENTO_ESCREVER: 'DOCUMENTO_ESCREVER',
  GERADOR_LER: 'GERADOR_LER',
  GERADOR_ESCREVER: 'GERADOR_ESCREVER',
  EMPRESA_LER: 'EMPRESA_LER',
  EMPRESA_ESCREVER: 'EMPRESA_ESCREVER',
  HISTORICO_LER: 'HISTORICO_LER',
  RELATORIO_LER: 'RELATORIO_LER',
  USUARIO_LER: 'USUARIO_LER',
  USUARIO_ESCREVER: 'USUARIO_ESCREVER',
  UNIDADE_LER: 'UNIDADE_LER',
  UNIDADE_ESCREVER: 'UNIDADE_ESCREVER',
  PERMISSAO_LER: 'PERMISSAO_LER',
  PERMISSAO_ESCREVER: 'PERMISSAO_ESCREVER',
  INSTITUICAO_ESCREVER: 'INSTITUICAO_ESCREVER',
  CHAT_USAR: 'CHAT_USAR',
  RELATORIO_PROF_ENVIAR: 'RELATORIO_PROF_ENVIAR',
  RELATORIO_PROF_LER: 'RELATORIO_PROF_LER',
  RELATORIO_PROF_COBRAR: 'RELATORIO_PROF_COBRAR',
} as const;

export type CodigoPermissao = (typeof PERMISSOES)[keyof typeof PERMISSOES];

/** Nome amigável dos módulos da matriz de permissões. */
export const ROTULO_MODULO: Record<string, string> = {
  AGENDA: 'Agenda',
  SECRETARIA: 'Secretaria',
  ATENDIMENTOS: 'Atendimentos',
  PROJETOS: 'Projetos',
  DOCUMENTOS: 'Documentos',
  GERADOR: 'Gerador de documentos',
  EMPRESAS: 'Empresas',
  HISTORICO: 'Histórico',
  RELATORIOS: 'Relatórios',
  USUARIOS: 'Usuários',
  UNIDADES: 'Unidades',
  PERMISSOES: 'Permissões',
  CHAT: 'Chat',
};
